# Generated by Django 4.2 on 2023-10-12 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 14, 22, 16, 668674, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
