# Generated by Django 4.2 on 2023-08-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.IntegerField(default=0, help_text='Valeur, en centimes.'),
        ),
    ]
