# Generated by Django 4.2.8 on 2024-01-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutstripe',
            name='status',
            field=models.CharField(choices=[('O', 'En attente de paiement'), ('E', 'Expiré'), ('P', 'Payé'), ('W', 'Wallet primaire chargé'), ('V', 'Wallet user chargé'), ('C', 'Annulée'), ('R', 'en erreur')], default='O', max_length=1, verbose_name='Statut de la commande'),
        ),
    ]
