# Generated by Django 4.2 on 2023-08-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedowuser',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='fedow_core.wallet'),
        ),
    ]
