# Generated by Django 4.2 on 2023-10-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('TLF', 'Fiduciary local token'), ('TNF', 'Token local non fiduciaire'), ('FED', 'Fiduciary and federated token on stripe'), ('MEM', 'Membership or subscription')], max_length=3),
        ),
    ]
