# Generated by Django 4.2 on 2023-08-02 09:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('wallet', 'asset')},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_received', to='fedow_core.wallet')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_sent', to='fedow_core.wallet')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fedow_core.token')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
