# Generated by Django 4.2 on 2023-08-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0002_alter_fedowuser_wallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NFCCard',
            new_name='Card',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
