# Generated by Django 4.2 on 2023-10-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0002_alter_asset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('F', 'Premier bloc'), ('S', "Vente d'article"), ('C', 'Creation monétaire'), ('R', 'Recharge'), ('T', 'Transfert')], default='S', max_length=1),
        ),
    ]
