# Generated by Django 4.2 on 2023-08-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0002_alter_token_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='federated_primary',
            field=models.BooleanField(default=False, editable=False, help_text='Asset primaire équivalent euro.'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('federated_primary', True)), fields=('federated_primary',), name='unique_federated_primary_asset'),
        ),
    ]
