# Generated by Django 4.2.8 on 2024-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0003_configuration_create_place_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='private_pem',
            field=models.CharField(blank=True, editable=False, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='public_pem',
            field=models.CharField(blank=True, editable=False, max_length=512, null=True),
        ),
    ]
