# Generated by Django 4.2.8 on 2024-02-20 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0004_alter_wallet_private_pem_alter_wallet_public_pem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='create_place_apikey',
            field=models.OneToOneField(help_text='Clé API root de la billetterie qui permet de créer des nouveau lieux', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='fedow_core.createplaceapikey'),
        ),
    ]
