# Generated by Django 4.2.8 on 2024-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0005_alter_configuration_create_place_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lespass_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
