# Generated by Django 4.2.8 on 2024-03-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0006_place_lespass_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutstripe',
            name='checkout_session_id_stripe',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutstripe',
            name='status',
            field=models.CharField(choices=[('N', 'Créée'), ('O', 'En attente de paiement'), ('E', 'Expiré'), ('P', 'Payé'), ('W', 'Wallet primaire chargé'), ('V', 'Wallet user chargé'), ('C', 'Annulée'), ('R', 'en erreur')], default='N', max_length=1, verbose_name='Statut de la commande'),
        ),
    ]
