# Generated by Django 4.2.8 on 2024-04-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0008_remove_place_lespass_url_place_lespass_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('TLF', 'Fiduciaire'), ('TNF', 'Cadeau'), ('FED', 'Fiduciaire fédérée'), ('TIM', 'Monnaie temps'), ('FID', 'Points de fidélité'), ('BDG', 'Badgeuse/Pointeuse'), ('SUB', 'Adhésion ou abonnement')], max_length=3),
        ),
        migrations.AlterField(
            model_name='checkoutstripe',
            name='status',
            field=models.CharField(choices=[('N', 'Créée'), ('O', 'En attente de paiement'), ('G', 'En cours de traitement'), ('P', 'Payé'), ('E', 'Expiré'), ('W', 'Wallet primaire chargé'), ('V', 'Wallet user chargé'), ('C', 'Annulée'), ('R', 'en erreur')], default='N', max_length=1, verbose_name='Statut de la commande'),
        ),
    ]
