# Generated by Django 4.2.8 on 2024-05-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0009_alter_asset_category_alter_checkoutstripe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stripe_api_key',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
