# Generated by Django 4.2 on 2024-11-26 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0012_asset_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='wallet_origin',
            field=models.ForeignKey(help_text="Lieu ou configuration d'origine", on_delete=django.db.models.deletion.PROTECT, related_name='assets_created', to='fedow_core.wallet'),
        ),
    ]
