# Generated by Django 4.2 on 2025-04-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0013_alter_asset_wallet_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('FST', 'Premier bloc'), ('SAL', "Vente d'article"), ('CRE', 'Creation monétaire'), ('REF', 'Recharge'), ('TRF', 'Transfert'), ('SUB', 'Abonnement ou adhésion'), ('BDG', 'Badgeuse'), ('FUS', 'Fusion de deux wallets'), ('RFD', 'Remboursement'), ('VID', 'Dissocciation de la carte et du wallet user'), ('BNK', 'Remise en banque')], default='SAL', max_length=3),
        ),
    ]
