# Generated by Django 4.2.22 on 2025-06-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0014_alter_transaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutstripe',
            name='status',
            field=models.CharField(choices=[('N', 'Créée'), ('O', 'En attente de paiement'), ('G', 'En cours de traitement'), ('P', 'Payé'), ('E', 'Expiré'), ('W', 'Wallet primaire chargé'), ('V', 'Wallet user chargé'), ('C', 'Annulée'), ('R', 'en erreur'), ('F', 'Remboursé')], default='N', max_length=1, verbose_name='Statut de la commande'),
        ),
    ]
