# Generated by Django 4.2.22 on 2025-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0016_alter_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('FST', 'Premier bloc'), ('SAL', "Vente d'article"), ('QRS', 'Vente via QrCode'), ('CRE', 'Creation monétaire'), ('REF', 'Recharge'), ('TRF', 'Transfert'), ('SUB', 'Abonnement ou adhésion'), ('BDG', 'Badgeuse'), ('FUS', 'Fusion de deux wallets'), ('RFD', 'Remboursement'), ('VID', 'Dissocciation de la carte et du wallet user'), ('BNK', 'Remise en banque')], default='SAL', max_length=3),
        ),
    ]
