# Generated by Django 4.2.22 on 2025-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0018_alter_checkoutstripe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutstripe',
            name='intent_payment_id_stripe',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True),
        ),
    ]
