# Generated by Django 4.2.22 on 2025-09-01 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0019_checkoutstripe_intent_payment_id_stripe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutstripe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_stripe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='checkout_stripe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='fedow_core.checkoutstripe'),
        ),
    ]
