# Generated by Django 4.2.22 on 2025-09-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0020_alter_checkoutstripe_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutstripe',
            name='invoice_stripe_id',
            field=models.CharField(blank=True, editable=False, max_length=27, null=True),
        ),
    ]
