# Generated by Django 4.2.22 on 2026-05-25 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0022_alter_transaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationapikey',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='fedow_core.place'),
        ),
        migrations.AlterField(
            model_name='organizationapikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
