# Generated by Django 4.2.30 on 2026-07-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0024_alter_transaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutstripe',
            name='checkout_session_id_stripe',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
    ]
