# Generated by Django 4.2.30 on 2026-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0025_alter_checkoutstripe_checkout_session_id_stripe'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['asset', 'datetime'], name='transaction_asset_datetime'),
        ),
    ]
