# Generated by Django 4.2.30 on 2026-09-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedow_core', '0026_transaction_transaction_asset_datetime'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('action__in', ['CRE', 'REF']), ('checkout_stripe__isnull', False)), fields=('checkout_stripe', 'action'), name='une_seule_creation_et_un_seul_refill_par_checkout'),
        ),
    ]
